# Generated by Django 5.2.9 on 2026-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_productstock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(blank=True, help_text='Snapshot of product SKU at time of order', max_length=50, null=True),
        ),
    ]
