# Generated by Django 5.2.9 on 2025-12-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_color_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsizevariant',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ProductColorVariant',
        ),
        migrations.DeleteModel(
            name='ProductSizeVariant',
        ),
    ]
