# Generated by Django 5.2.9 on 2026-01-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_delivery_otp_order_otp_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_type',
            field=models.CharField(choices=[('normal', 'Normal Delivery'), ('return', 'Return Pickup'), ('refund', 'Refund Pickup'), ('exchange', 'Exchange Pickup')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('rejected', 'Rejected'), ('out_for_delivery', 'Out For Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('exchanged', 'Exchanged')], default='pending', max_length=20),
        ),
    ]
