# Generated by Django 5.2.9 on 2025-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storecategory_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
