# Generated by Django 5.2.9 on 2026-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddress_latitude_useraddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
