# Generated by Django 5.2.9 on 2026-01-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_orderitem_image1_alter_orderitem_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
