# Generated by Django 5.2.9 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_orderitem_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
