# Generated by Django 5.2.9 on 2026-02-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.storecategory'),
            preserve_default=False,
        ),
    ]
