# Generated by Django 5.2.9 on 2026-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orderitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_store_owner',
            field=models.BooleanField(default=False),
        ),
    ]
