# Generated by Django 5.2.9 on 2026-02-13 06:05

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_category_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='store', chained_model_field='store_category__stores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subcategory'),
        ),
    ]
