# Generated by Django 5.2.9 on 2026-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
