# Generated by Django 5.2.9 on 2026-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, to='accounts.product'),
        ),
    ]
