# Generated by Django 5.2.9 on 2026-02-13 11:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
