# Generated by Django 5.2.9 on 2026-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_category_icon_category_icon_url_subcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
