# Generated by Django 5.2.9 on 2026-02-14 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
