# Generated by Django 5.2.9 on 2026-02-16 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bus_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bus_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
