# Generated by Django 5.2.9 on 2026-02-16 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_is_bus_partner_order_bus_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bus_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bus_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bus_number_plate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=20)),
                ('route_district', models.CharField(max_length=100)),
                ('route_block', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
