# Generated by Django 5.2.9 on 2026-02-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_order_bus_mobile_order_bus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
