# Generated by Django 5.2.9 on 2026-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_order_delivery_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
