# Generated by Django 5.2.9 on 2026-02-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_delivery_district_order_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.bus'),
        ),
    ]
