# Generated by Django 5.2.9 on 2026-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('assigned', 'Assigned'), ('bus_assigned', 'Bus Partner Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('rejected', 'Rejected'), ('out_for_delivery', 'Out For Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('exchanged', 'Exchanged')], default='pending', max_length=20),
        ),
    ]
