# Generated by Django 5.2.9 on 2026-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bus_assigned_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
